[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 5, y = 2 }
class = { instance = "Alacritty", general = "Alacritty" }

position = "None"
dynamic_padding = true
decorations = "Full"
opacity = 1
blur = true
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"
resize_increments = false
option_as_alt = "None"
level = "Normal"


[scrolling]
multiplier = 3
history = 10_000

[font]
builtin_box_drawing = true
size = 11

offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[general]
import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]
